name: "Action name"
description: "Action description"
author: "Freckle"
inputs:
  github-token:
    description: "Override GitHub token, if necessary"
    required: true
    default: "${{ github.token }}"
runs:
  using: "node20"
  main: "dist/index.js"
