name: Mergeabot

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
    
permissions:
  contents: write
  pull-requests: write # so we add comment from Dependabot

jobs:
  mergeabot:
    runs-on: ubuntu-latest
    steps:
      - uses: freckle/mergeabot-action@v1
        with:
          quarantine-days: -1
